##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby

Vagrant.configure("2") do |config|
  config.vm.box = "takahiro-itou/centos7-quantum"

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-centos7-quantum"
    v.memory = "2048"
  end

  config.vm.synced_folder(".", "/vagrant", disabled: true)

end
